export const productConstants ={
    PRODUCT_CREATE_REQUEST : "PRODUCT_CREATE_REQUEST",
    PRODUCT_CREATE_SUCCESS :"PRODUCT_CREATE_SUCCESS",
    PRODUCT_CREATE_FAILURE : 'PRODUCT_CREATE_FAILURE',
    PRODUCT_GET_REQUEST : 'PRODUCT_GET_REQUEST',
    PRODUCT_GET_SUCCESS : 'PRODUCT_GET_SUCCESS',
    PRODUCT_GET_FAIUTRE : 'PRODUCT_GET_FAILURE',
    PRODUCT_UPDATE_REQUEST : 'PRODUCT_UPDATE_REQUEST',
    PRODUCT_UPDATE_SUCCESS : 'PRODUCT_UPDATE_SUCCESS',
    PRODUCT_UPDATE_FAILURE : 'PRODUCT_UPDATE_FAILURE',
    PRODUCT_DELETE_REQUEST : 'PRODUCT_DELETE_REQUEST',
    PRODUCT_DELETE_SUCCESS : 'PRODUCT_DELETE_SUCCESS',
    PRODUCT_DELETE_FAILURE : 'PRODUCT_DELETE_FAILURE',
}
export const userConstants = {
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
}